INSERT INTO "SQLDATA"("ID", "ACADDRESS", "ACUSER", "ACPASSWORD", "ACSURFACE", "ACZL") VALUES ('3', '127.0.0.1', 'hr3', 'hr', 'HR', '1');
INSERT INTO "SQLDATA"("ID", "ACADDRESS", "ACUSER", "ACPASSWORD", "ACSURFACE", "ACZL") VALUES ('1', '127.0.0.1', 'hr1', 'hr', 'HR', '1');
INSERT INTO "SQLDATA"("ID", "ACADDRESS", "ACUSER", "ACPASSWORD", "ACSURFACE", "ACZL") VALUES ('2', '127.0.0.1', 'hr2', 'hr', 'HR', '1');
INSERT INTO "SQLDATA"("ID", "ACADDRESS", "ACUSER", "ACPASSWORD", "ACSURFACE", "ACZL") VALUES ('4', '3', '2', '2', '2', '2');
INSERT INTO "SQLDATA"("ID", "ACADDRESS", "ACUSER", "ACPASSWORD", "ACSURFACE", "ACZL") VALUES ('5', '4', '2', '2', '2', '3');
INSERT INTO "SQLDATA"("ID", "ACADDRESS", "ACUSER", "ACPASSWORD", "ACSURFACE", "ACZL") VALUES ('21', '127.0.0.1', 'hr', 'hr', 'HR', '1');
